Fix for Microcks template Keycloak realm file to support Microcks 1.0.0 onwards
Apicurio/apicurio-studio pull request #1323
Opened 2020-11-16 05:39 UTC by narioinc

@EricWittmann 

I am creating this pull request for the fix to the Microcks realm template file to as to fix the bug #1319. The Fix proposes that with Microcks 1.0.0, role definitions have moved from the realm scope to the microcks-app client scope so that it is easier to plug Microcks on an existing realm.

**PR tested on the following environment:**
Environment - Ubuntu 20.04
APICurio release - BETA 2.465
Affected artefact - Microcks realm config JSON file
Potential fix available - Yes
Fix tested on - Ubuntu 20.04

@lbroudoux would like to review this PR along with you to ensure correctness. Thanks

2020-11-16 16:51 UTC, EricWittmann commented
@lbroudoux Does this look good to you?

2020-11-18 10:06 UTC, lbroudoux requested changes
The `user` roles is defined twice and the `admin` and `manager` roles are missing. Also I don't see where the `user` role is defined as a default for the `microcks-app` client.

As this template should be the result of a Keycloak export, it is quite hard to understand and diff because of all the ids and optional attributes. Wouldn't it be possible to use a simpler form like in https://github.com/microcks/microcks/blob/master/install/docker-compose/keycloak-realm/microcks-realm-sample.json ?  I'll try re-used an older Keycloak version to test things up becase we've switcher to v10.1 on the Microcks side.

2020-11-18 10:06 UTC, lbroudoux commented on distro/docker-compose/config/keycloak/microcks-realm.json.template
> +        }
To be fully aligned, we should also add the `manager` and `admin` roles as in https://github.com/microcks/microcks/blob/master/install/docker-compose/keycloak-realm/microcks-realm-sample.json#L65

2020-11-18 10:06 UTC, lbroudoux commented on distro/docker-compose/config/keycloak/microcks-realm.json.template
> +    },
This is not related to a Microcks requirement

2020-11-18 13:07 UTC, narioinc commented
@lbroudoux  @EricWittmann  I guess the template file can be changed to the version that is there in microcks github.
Since I saw that the current template file seems to have been created from an export with all the finer details, I too took did a export and sent in a PR. 
I will create a PR with just the realm config provided mi microcks team here
https://github.com/microcks/microcks/blob/master/install/docker-compose/keycloak-realm/microcks-realm-sample.json

2020-11-18 13:15 UTC, narioinc commented
I have changed the file to reflect the correct concise template needed for the Microcks app to run. Checked a quick install it works on my environment

2020-11-19 21:01 UTC, EricWittmann approved these changes
LGTM waiting for @lbroudoux to approve.

2020-11-20 09:58 UTC, lbroudoux approved these changes

2020-11-20 09:58 UTC, lbroudoux commented
LGTM too ! Thanks @narioinc for PR !

2020-11-20 11:18 UTC, narioinc commented
thanks @lbroudoux for the review and approval !

2020-11-23 14:07 UTC, merged