Move API template delivery from studio-fe-studio to studio-be-hub-api
Apicurio/apicurio-studio pull request #1595
Opened 2021-07-16 15:16 UTC by DyspC

Hello, 

This is a first part for #1562, moving the static templates from the frontend to the backend.

2021-07-20 17:35 UTC, EricWittmann commented on front-end/studio/src/app/services/template.service.ts
>      public getTemplates(type: string): ApiDesignTemplate[] {
I think this needs to return a `Promise<ApiDesignTemplate[]>` if we're going to possibly be fetching the data from the server now (when not cached).

2021-07-20 17:37 UTC, EricWittmann commented on back-end/hub-api/src/main/java/io/apicurio/hub/api/rest/impl/TemplatesResource.java
> +    private static final List<ApiTemplate> allTemplates = List.of(
Let's store each template as a resource instead of inlining them in the Java code.  We can load the resources in a `static` intializer.

2021-07-20 17:37 UTC, EricWittmann requested changes
Looks good!  I had a couple of comments, let me know what you think.

2021-07-23 14:43 UTC, DyspC commented
I'm not sure about the way to handle promises but wdyt?

2021-07-23 17:49 UTC, EricWittmann commented
Awesome @DyspC !  This is great, almost perfect.  The only change I would ask for is to keep the `templateCache` as a cache of "" instead of caching the `Promise`.  Instead, the logic of the method should check the cache, and use `Promise.resolve()` in the case of a cache hit.  Something like this:

```typescript

    private templateCache: { [key: string]: ApiDesignTemplate[] } = {};

    public getTemplates(type: string): Promise<ApiDesignTemplate[]> {
        if (!this.templateCache.hasOwnProperty(type)) {
            console.info(`[TemplateService] Templates of type '${type}' are not ready, loading them from the API...`)
            let options: any = this.options({ "Accept": "application/json" });
            // Fetch the template from the server, return a Promise since the REST call is async.
            return this.httpGet<any>(this.endpoint("/templates", {}, { type: type }), options)
                .then(rawTemplates => {
                    let rval: ApiDesignTemplate[] = [];
                    for (let template of rawTemplates) {
                        rval.push({
                            type: template.type,
                            name: template.name,
                            description: template.description,
                            content: template.document
                        })
                    }
                    
                    // Cache the templates for this type.
                    this.templateCache[type] = rval;
                    return rval;
                });
        }
        return this.templateCache[type];
    }

```

2021-07-23 19:13 UTC, DyspC commented
I'm not sure, I copy pasted this but it makes the tab poll for templates until it crashes (cache hits but nothing is displayed).

2021-07-30 17:44 UTC, EricWittmann commented
@carlesarnal if you have some time in the next 2 weeks can you help with this?  @DyspC I'm going to be on vacation for a bit, hopefully Carles can help out!  :)

2021-08-16 18:59 UTC, EricWittmann commented
FYI I'm back from PTO and trying to get some eyeballs on this, sorry for the delay @DyspC

2021-08-18 09:35 UTC, carlesarnal commented
Hi, @DyspC I have tested this locally in both chrome and firefox and it's working fine for me. Do you have more info about your setup? I'm testing using the Quarkus build.

2021-08-18 10:34 UTC, carlesarnal commented
> Hi, @DyspC I have tested this locally in both chrome and firefox and it's working fine for me. Do you have more info about your setup? I'm testing using the Quarkus build.

Just FYI, I have also tested this using the quickstart and it also works.

2021-08-18 15:03 UTC, carlesarnal commented
Hi, as a recap,

I've been able to reproduce the issue, I wasn't able to do it due to a code mismatch.

I have solved the problem by propagating the array of elements instead of the promise itself. I think this is the right thing to do. If we cache elements, we propagate elements, if we cache promises, then we propagate promises.

2021-08-18 15:36 UTC, DyspC commented
> > Hi, @DyspC I have tested this locally in both chrome and firefox and it's working fine for me. Do you have more info about your setup? I'm testing using the Quarkus build.
> 
> Just FYI, I have also tested this using the quickstart and it also works.

Were you testing the raw branch or after applying Eric's suggestion? I just tried the patch again with Brave/Safari and my dev mode / the quickstart and both² get the tab hang issue.

Also it looks like 5ad41d6 and b585e61 cancel themselves so we're back to this remark https://github.com/Apicurio/apicurio-studio/pull/1595#discussion_r673342029

2021-08-18 15:47 UTC, carlesarnal commented
> > > Hi, @DyspC I have tested this locally in both chrome and firefox and it's working fine for me. Do you have more info about your setup? I'm testing using the Quarkus build.
> > 
> > 
> > Just FYI, I have also tested this using the quickstart and it also works.
> 
> Were you testing the raw branch or after applying Eric's suggestion? I just tried the patch again with Brave/Safari and my dev mode / the quickstart and both² get the tab hang issue.
> 
> Also it looks like [5ad41d6](https://github.com/Apicurio/apicurio-studio/commit/5ad41d66edb42ce3902dc0b13239e7e19c7c934b) and [b585e61](https://github.com/Apicurio/apicurio-studio/commit/b585e61fdba4be8bf6b9a87f0fb109a0bc93155b) cancel themselves so we're back to this remark [#1595 (comment)](https://github.com/Apicurio/apicurio-studio/pull/1595#discussion_r673342029)

I was testing the raw branch, that's why I wasn't getting the error, after applying the patch I'm getting the error.

2021-08-18 16:06 UTC, EricWittmann commented
OK everyone - sorry about this.  It has been a little while since I've done any Angular development, and I forgot how it works.  :)  I've made some changes so that the templates are loaded asynchronously during the "LoadAsyncPageData" phase of the page load.  So now the form component just gets the templates from the template service and doesn't deal with promises or anything.  The template service caches the templates in a "load" step, which is triggered (and waited on) by the Create page's async load phase.

My suggestion did not work due to how angular renders a page - specifically how it re-renders a page!  As a result, angular was just calling the `templates()` method again and again.  Because each time it called that method, a new `Promise` was being returned (my bad on that).  Caching the `Promise` instead of the data was actually working.

In any case, the approach I"m going with is, I think, better in the specific context of the Studio application (not necessarily Angular in general).  :)

2021-08-18 16:06 UTC, EricWittmann commented
Thank you @DyspC for the contribution - sorry it's taken so long to get it merged!

2021-08-18 16:06 UTC, merged

2021-08-18 16:08 UTC, EricWittmann commented
If interested, here is my change:  https://github.com/Apicurio/apicurio-studio/commit/38a8609513cb173ad357292bcec9f59f38365b7b

2021-08-18 16:08 UTC, EricWittmann commented
It includes a UI spinner in case the loading of the templates takes some time for some reason.